### ISSUE TITLE
牌力问题

### ISSUE THREAD

**Issue by defddr** [skyduy/ddz_moves#2]
你好，看代码demo
似乎都没区分地主和农民身份，
该demo是不是目前只关注 压牌和出牌分牌等操作的正确定，但是胜利不做要求？是吗？
谢谢！

**Comment by skyduy** [comment]
@defddr 
你好。

你理解的正确，该 demo 只是个出牌引擎。
函数接受两个参数，一个是当前自己手里的牌，一个是上家的出牌，返回所有的可执行操作。
而地主/农民身份、玩家手里的牌、玩家出牌模型，则需要使用者自己维护。

在 RL 框架中，本 ddz 模块充当状态转化“引擎”。

**Comment by defddr** [comment]
了解，谢谢您的解答
